version: '3'

services:
  amazonpg:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'amazonpg'
    restart: always
    volumes:
      - amazonpg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  amazonpg-data:
